# ArchAngel docker-compose
version: '3'
services:
    mongo:
        image: mongodb:seeded
        container_name: seededdb
        tty: true
        stdin_open: true
        restart: always

    service:
        image: archangelms
        container_name: archangelms
        links:
            - mongo:seededdb
        tty: true
        stdin_open: true
        restart: always

    nginx:
        image: archangelui
        container_name: archangelui
        ports:
            - 10080:8080
        links:
            - service:archangelms
        tty: true
        stdin_open: true
        restart: always
